#开发配置文件
#配置mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vedio-master?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: opr416

  # 开发环境下，websocket线程池配置
  websocket:
    task:
      execution:
        pool:
          # 配置线程池的长度为10，最大长度为30，线程池中队列的长度为1000
          coreSize: 5
          maxSize: 15
          queueLength: 1000


# 开发流程中，直接将sql语句打印到控制台，方便调试
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 开发环境端口号
server:
  port: 8089
  servlet:
    context-path: "/video-master"
    encoding:
      charset: UTF-8